name: trackbuzz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.7
  bloc: ^9.0.1
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  intl: ^0.20.2
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  flutter_local_notifications: ^19.4.0
  flutter_background_service: ^5.1.0
  timezone: ^0.10.1
  permission_handler: ^12.0.1
  archive: ^4.0.7
  file_picker: ^10.3.3
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/img/